name: Clone Kernel
description: Clone Kernel

inputs:
  branch:
    description: 'Kernel branch (e.g., android15-6.6)'
    required: true

runs:
  using: composite

steps:
  - name: Clone SUSFS and change commit if necessary, clone kernel patches
    shell: bash
    run: |
      git clone https://android.googlesource.com/kernel/common.git --single-branch --depth 1 -b ${{ inputs.branch }}
