name: Build

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Choose Release Type"
        required: true
        type: choice
        options:
          - Actions
          - Pre-Release
          - Release
        default: Actions
      
      ksu-next:
        description: "Build with KSU-Next?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      susfs:
        description: "Build with SUSFS?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      bbg:
        description: "Build with BBG?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      zeromount:
        description: "Add Zeromount?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      unicode_fix:
        description: "Add unicode fix?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      droidspace:
        description: "Add droidspace support?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      ntsync:
        description: "Add ntsync?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no
      
      kernel_optimizations:
        description: "Add optimizations from kernel patches repo?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: no

jobs:
  build-a366e:
    name: "A366E-${{ matrix.version }}-${{ matrix.branch }}"
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: "android15-6.6-2025-03_r33"
            version: "A366EXXU4BYI7"

    uses: ./.github/workflows/a366e.yml
    secrets: inherit
    with:
      clang_version: "r510928"
      branch: ${{ matrix.branch }}
      version: ${{ matrix.version }}
      
      ksu-next: ${{ inputs.ksu-next }}
      susfs: ${{ inputs.susfs }}
      bbg: ${{ inputs.bbg }}
      zeromount: ${{ inputs.zeromount }}
      unicode_fix: ${{ inputs.unicode_fix }}
      droidspace: ${{ inputs.droidspace }}
      ntsync: ${{ inputs.ntsync }}
      kernel_optimizations: ${{ inputs.kernel_optimizations }}
